server:
    port:
      8093

jasypt:
  encryptor:
    password: 123456!@#

info:
  username: ENC(fjuvNsVtpQvRW2jNxq056A==)
  password: ENC(AQCRU09RMOj5ommAw5OHEg==)



food:
  rice: 米饭
  meat: 烤肉${random.int}
  sauce:
    - 咖喱
    - 香辣
    - 原味

#spring:
#  profiles:
#    active: dev
#
#
#---
#spring:
#  profile: dev
#
#server:
#  port: 8090
#
#---
#spring:
#  profile: prod
#
#server:
#    port: 8010


